language: csharp
script:
  - xbuild /p:Configuration=Debug /src/PasswordManager.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore /src/PasswordManager.sln
after_script:
  - nunit-console Tests/bin/Debug/Tests.dll